<?php
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function yahoo_help($path, $arg) {
  switch ($path) {
    case "admin/help#coursera":
      return '<p>' . t("Displays all coursera listes courses!!") . '</p>';
      break;
  }
} 

/*
 * Implementation of hook_menu()
 */
function yahoo_menu()
{
  $items['course'] = array(
    'title' => 'Course Listed',
    'description' => 'Simple hook menu implementation',
    'page callback' => 'my_list_function',
    'access arguments' => array('access content'),
  );
  return $items;
}

function my_list_function(){
   return theme('my_custom_template');
}

/*
 * Implementation of hook_theme().
 */

function yahoo_theme(){
  return array(
    'my_custom_template' => array(
       'template' => 'custom-page',
     ),
  );
}
